language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
before_install:
  - export TZ=Europe/London
script:
  - yarn test-travis
after_script:
  - coveralls < coverage/lcov.info
